#define I2C_SENSOR_SDA PB_7
#define I2C_SENSOR_SCL PB_6
#define RS422_RX PA_10
#define RS422_TX PA_9
#define DEBUG_RX PA_3
#define DEBUG_TX PA_2
#define STATE_LED_RED PA_8
#define STATE_LED_GREEN PC_9
#define STATE_LED_BLUE PC_8
#define BP1_IGNITE PC_7
#define BP1_CONT   PC_6
#define BP2_IGNITE PB_15
#define BP2_CONT   PB_14
#define BP3_IGNITE PB_13
#define BP3_CONT   PB_12
#define BP4_IGNITE PB_1
#define BP4_CONT   PB_0
#define BP5_IGNITE PC_5
#define BP5_CONT   PC_4
#define BP6_IGNITE PA_7
#define BP6_CONT   PA_6
#define BP7_IGNITE PA_5 
#define BP7_CONT   PA_4